baseURL: "http://localhost:1313/"
theme: "up"
languageCode: "en-us"
title: "Create Community"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Create Community"
  description: "A community-oriented workspace providing the tools and resources for (almost) any project you can think of."
  images:
    - "images/logo.png"

  logo: "images/icon.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    instagram: "https://www.instagram.com/create.community.society"
    # discord: "https://discord.gg/xqfM4sezCr"
    # patreon: "https://www.patreon.com/CreateCommunity"

  image:
    - "images/workspaces.png"
    - "images/logo.png"

  location:
    map: "https://maps.app.goo.gl/BJfZmsSkuNhqyTPUA"
    address: "CanScribe College,
      1226 Ellis Street, Kelowna, BC"

  contact:
    - "info@createcommunity.space"

  hours:
    - day: "Monday"
      time: "closed"

    - day: "Tueday"
      time: "closed"

    - day: "Wednesday"
      time: "5pm-9pm"

    - day: "Thursday"
      time: "closed"

    - day: "Friday"
      time: "closed"

    - day: "Saturday"
      time: "closed"

    - day: "Sunday"
      time: "closed"

  copyright: "© 2025 Create Community Members, all rights reserved"

menus:
  main:
    - name: "Home"
      url: "/#"
      weight: 1

    - name: "Who We Are"
      url: "/who-we-are"
      weight: 2

    - name: "Community"
      weight: 3

    - name: Locations
      url: "/locations"
      parent: Community
      weight: 1

    - name: Workshops
      url: "/workshops"
      parent: Community
      weight: 2

    - name: Substack
      url: "/substack"
      parent: Community
      weight: 3

    # buttons:
    #   - name: "Book a call"
    #     url: "/#"
    #     weight: 5
    #     pre: "btn btn-primary text-light"

    - name: "FAQs"
      url: "/faqs"
      weight: 4

    - name: "Our Team"
      url: "/our-team"
      weight: 5

  footer:
    - name: "Who We Are"
      url: "/who-we-are"
      weight: 1

    - name: "FAQs"
      url: "/faqs"
      weight: 2

    - name: "Our team"
      url: "/our-team"
      weight: 3

    # - name: "Pricing"
    #   url: "/pricing"
    #   weight: 4

    # - name: "Contact Us"
    #   url: "/contact-us"
    #   weight: 5

taxonomies:
  series: "series"
  tags: "tags"

markup:
  goldmark:
    renderer:
      unsafe: true
include: [".well-known"]
